### ISSUE TITLE
Where are you hosting the starrocks airbyte connector container?

### ISSUE THREAD

**Issue by alberttwong** [liuzhongjun89/starrocks-airbyte-connector#4]
Per https://docs.airbyte.com/connector-development/tutorials/build-a-connector-the-hard-way#4-test-the-connector, you build a container, deploy the container somewhere and then in the airbyte UI, point to the container to move data from source to sink.   Who will publish the container?   You or StarRocks?

**Comment by liuzhongjun89** [comment]
We build it from source locally  and add new connector with the container  in the airbyte by UI just now, so we can use it.

**Comment by alberttwong** [comment]
I read in the instructions that you build once and then deploy the container in docker hub.    If you don't want to deploy in your own docker hub account, I will ask StarRocks engineering to upload into their docker hub account.

**Comment by alberttwong** [comment]
For testing, I uploaded it to `atwong/destination-starrocks:latest` and will move to starrocks' docker hub later.

**Comment by alberttwong** [comment]
we moved this to https://hub.docker.com/r/starrocks/destination-starrocks
